### PR TITLE
Read .todo at TODO_DIR prior to HOME

### PR DESCRIPTION
**Pull request by naoty**
I want to put .todo file at the directory specified by `TODO_DIR` environment variable. It is useful to put .todo file into Dropbox and sync it.

### CODE REVIEW

**Comment by mattn** [comment]
@suzukaze do you have any opinion about this?

**Comment by suzukaze** [comment]
This PR is addintg a new TODO_DIR environment variable.
I don't understand the difference of TODO_DIR and  HOME.
if you set Dropbox file .todo in HOME, it syncs in Dropbox.

**Comment by naoty** [comment]
@suzukaze Do you mean that I should put a symbolic link to `$HOME/.todo` in the Dropbox folder? If so, your opnion also can solve my problem. This PR can be declined.

**Comment by suzukaze** [comment]
@naoty I'm sorry.

> Do you mean that I should put a symbolic link to $HOME/.todo in the Dropbox folder?

No.

I thought that we can set HOME in any dir but HOME is current user dir.
TODO_DIR is different from HOME.

I prefer to put TODO_DIR .todo file in Dropbox folder.

**Comment by naoty** [comment]
I see. if `TODO_DIR` isn't set, `$HOME/.todo` will be read. @mattn, would you merge this PR?

**Comment by suzukaze** [comment]
> Do you mean that I should put a symbolic link to $HOME/.todo in the Dropbox folder?

I cannot come this into my mind. It's nice idea.

**Pull request closed without merging**
